name: Access to private repo!!!
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: rumburakgit/gitjenkinsdemo1
      - run: |
           git ls-remote -h -t https://github.com/rumburakgit/gitjenkinsdemo1.git
#          date > generated.txt
#          git config user.name rumburakgit
#          git config user.email rumburak.eclipse@gmail.com
#          git add .
#          git commit -m "generated"
#          git push
#      - uses: actions/checkout@v1  
#        with:
#          repository: rumburakgit/gitjenkinsdemo1/tree/3.3.33
#          token: ${{ secrets.access-private-repos }}
#      - run: |
#          git ls-remote -h -t https://${{ secrets.access-private-repos }}@github.com/rumburakgit/gitjenkinsdemo1.git
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

