name: Report remaining open issues
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git ls-remote -h -t https://${{ secrets.access-private-repos }}@github.com/rumburakgit/gitjenkinsdemo1.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
