name: Access to private repo2 !!!
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
       path: main

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
       repository: rumburakgit/gitjenkinsdemo1/tree/3.3.33
       token: ${{ secrets.access-private-repos }}
